name: Execute linter

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  golang-ci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --skip-dirs-use-default=false -p bugs -D scopelint -p comment -D godox -p error -p format -D gofumpt -p import -D depguard -p metalinter -D revive -p performance -p sql -E testableexamples -E unparam -E asciicheck -E containedctx -E errname -E goconst -E ireturn -E nlreturn -E tenv -E testpackage -E usestdlibvars -E wastedassign -E whitespace -E wrapcheck -E wsl --exclude IfElseChain
          skip-cache: true
          version: v1.55.1
