name: Execute static code analysis

on: [ push, pull_request ]

jobs:
  static-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Static check
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.3"
